add getmin3nums function
BassemReda/SWE-git-assignment pull request #9
Opened 2018-11-29 22:22 UTC by alaaeldein108

2018-11-29 23:53 UTC, EhabMostafa reviewed
Please call you function in case 18 (Excute all)

2018-11-29 23:53 UTC, EhabMostafa commented on SWEgit/src/com/company/Main.java
> +    public static void getmin3nums(int[]arr)
The input will be string array in the main so i suggest to edit your function to be string array and covert this array to integer

2018-11-29 23:53 UTC, EhabMostafa commented on SWEgit/src/com/company/Main.java
> +		int[]temp=new int [arr.length];
Take temp of array before sort it

2018-12-01 08:32 UTC, abdallahsayed98 approved these changes

2018-12-01 08:34 UTC, abdallahsayed98 approved these changes

2018-12-01 09:16 UTC, EhabMostafa requested changes
Call you function in case 18

2018-12-01 11:13 UTC, EhabMostafa approved these changes

2018-12-01 11:14 UTC, merged